packageExtensions:
  "@atls-ui-parts/layout@*":
    dependencies:
      csstype: "*"
      styled-system: "*"
  "@atls-ui-parts/text@*":
    dependencies:
      "@emotion/styled": "*"
      "@types/react": "*"
      react: "*"
      styled-system: "*"

yarnPath: .yarn/releases/yarn-0.0.1-git.20220325.hash-c66fcd9.cjs
