packageExtensions:
  "@atls-ui-parts/layout@*":
    dependencies:
      "@emotion/styled": "*"
      csstype: "*"
      styled-system: "*"
  "@atls-ui-proto/theme@*":
    dependencies:
      "@emotion/css": "*"
  "@atls-ui-parts/text@*":
    dependencies:
      "@emotion/styled": "*"
      "@emotion/react": "*"
      "@types/react": "*"
      react: "*"
      styled-system: "*"
  "@emotion/styled@*":
    dependencies:
      "@emotion/react": "*"
      react: "*"

yarnPath: .yarn/releases/yarn-0.0.1-git.20230514.hash-af4cf64.cjs
